name: Deploy page
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    deploy-page:
        runs-on: ubuntu-latest
        env:
            CI: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Use Node.js 22.14.0
              uses: actions/setup-node@v4
              with:
                  node-version: "22.14.0"

            - name: Build and Deploy
              run: |
                npm i
                npm run predeploy
                npm run deploy

            

