name: Deploy page
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    env:
      CI: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js 22.14.0
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"

      - name: Build
        run: |
          npm i
          npm run predeploy

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build/

  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
